#!/usr/bin/env ruby

require 'json'
require 'yaml'

ROLE_NAME = 'org-mattbooks-rentchecks'

config = YAML.load_file("config/settings.yaml")

api_name = config['api_name']
function_name = config['status_function_name']

puts "API NAME: #{api_name}"

api_id = `aws apigateway create-rest-api --name #{api_name} --output text --query 'id'`.chomp

puts "API: #{api_id}"

resource_id = `aws apigateway get-resources --rest-api-id #{api_id} --output text --query 'items[?path==\`'/'\`].[id]'`.chomp

puts "RESOURCE: #{resource_id}"

schema = %[
{
  "type": "object",
  "properties": {
    "event_type": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      }
    }
  }
}
].tr("\n ", "")

`aws apigateway create-model --rest-api-id #{api_id} --name lobstatusupdate --schema '#{schema}' --content-type application/json`

`aws apigateway put-method --rest-api-id #{api_id} --resource-id #{resource_id} --http-method POST --authorization-type NONE --no-api-key-required --request-models '{"application/json":"lobstatusupdate"}'`

puts "In AWS console, set up request to use Lambda, pointing to your aws function #{function_name}"
puts "(Do not use Lambda Proxy)"


puts "In Integration Request section, set up a mapping for application/json with the following mapping:"

mapping = %[
#set($inputRoot = $input.path('$'))
{
  "eventType" : "$input.path('$.event_type.id')"
}
]

puts mapping
